### ISSUE TITLE
是否考虑到值的数据类型对缓存影响

### ISSUE THREAD

**Issue by Alozxy** [bobfang1992/vlog#1]
在使用map的时候，很少会使用到int型的value
一个cache行可以缓存8个int型数据，但是对于较长的结构体，可能就没有办法缓存多个实例，这样的情况下是否不同库的性能差距会减少？

**Comment by bobfang1992** [comment]
我感觉这个要具体看你的code然后做benchmark，你可以用我现在这个repo里的code试试（写一个复杂一点的struct）。但是我的直觉是google的实现还是要比stl的快。

**Comment by bobfang1992** [comment]
因为stl至少会有一次memory indrection，google的实现一次都没有。

**Comment by bobfang1992** [comment]
我先把这个关了，你要是尝试过有不同的发现欢迎回来我们一起交流研究~
